### ISSUE TITLE
setup download links on nairaland not working.

### ISSUE THREAD

**Issue by bot101** [bolorundurowb/Open-Exam-Suite-2.0#1]
the links you posted on nairaland.com for this project's setup.exe seem not to work, so no way to help in testing. I believe this project should already have its own website by now. Following keenly though.

**Comment by bolorundurowb** [comment]
Thank you so much. I'll begin working on a website for it. I'll also check the
links and get back to you. Thanks once again



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.0.42&pv=4.4.4] On Tue, Aug 18, 2015 at 11:00 PM, Okafor Ikenna < notifications@github.com [notifications@github.com] > wrote:
the links you posted on nairaland.com for this project's setup.exe seem not to
work, so no way to help in testing. I believe this project should already have
its own website by now. Following keenly though.

—
Reply to this email directly or view it on GitHub
[https://github.com/bolorundurowb/Open-Exam-Suite-2.0/issues/1] .[https://github.com/notifications/beacon/AJ9vq4pk3EGQ0LC76szmy5nVYpDnHSDjks5oo6JigaJpZM4Ft8AG.gif]
